package gregtechlite.gtlitecore.common.metatileentity.multiblock.generator

import gregtech.api.GTValues.MAX
import gregtech.api.GTValues.MAX_TRUE
import gregtech.api.GTValues.VOC
import gregtech.api.capability.impl.EnergyContainerList
import gregtech.api.capability.impl.MultiblockFuelRecipeLogic
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity
import gregtech.api.metatileentity.multiblock.FuelMultiblockController
import gregtech.api.metatileentity.multiblock.IMultiblockPart
import gregtech.api.metatileentity.multiblock.MultiblockAbility.IMPORT_FLUIDS
import gregtech.api.metatileentity.multiblock.MultiblockAbility.OUTPUT_ENERGY
import gregtech.api.metatileentity.multiblock.MultiblockAbility.OUTPUT_LASER
import gregtech.api.metatileentity.multiblock.MultiblockAbility.SUBSTATION_OUTPUT_ENERGY
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController
import gregtech.api.pattern.BlockPattern
import gregtech.api.pattern.FactoryBlockPattern
import gregtech.api.unification.material.Materials.Naquadria
import gregtech.client.renderer.ICubeRenderer
import gregtechlite.gtlitecore.api.recipe.GTLiteRecipeMaps.ANTIMATTER_GENERATOR_FUELS
import gregtechlite.gtlitecore.client.renderer.texture.GTLiteOverlays
import gregtechlite.gtlitecore.common.block.variant.GlassCasing
import gregtechlite.gtlitecore.common.block.variant.MetalCasing
import gregtechlite.gtlitecore.common.block.variant.MultiblockCasing
import net.minecraft.client.resources.I18n
import net.minecraft.item.ItemStack
import net.minecraft.util.ResourceLocation
import net.minecraft.world.World
import net.minecraftforge.fml.relauncher.Side
import net.minecraftforge.fml.relauncher.SideOnly

class MultiblockAntimatterGenerator(id: ResourceLocation) : FuelMultiblockController(id, ANTIMATTER_GENERATOR_FUELS, MAX)
{

    init
    {
        recipeMapWorkable = AntimatterGeneratorWorkableHandler(this)
        recipeMapWorkable.maximumOverclockVoltage = VOC[MAX_TRUE] // Long.MAX_VALUE
    }

    companion object
    {
        private val casingState = MetalCasing.QUANTUM_ALLOY.state
        private val secondCasingState = MultiblockCasing.GRAVITY_STABILIZATION_CASING.state
        private val thirdCasingState = MultiblockCasing.ADVANCED_FILTER_CASING.state
        private val coilState = MultiblockCasing.ANTIMATTER_ANNIHILATION_MATRIX.state
        private val secondCoilState = MultiblockCasing.PROTOMATTER_ACTIVATION_COIL.state
        private val glassState = GlassCasing.ANTIMATTER_CONTAINMENT.state
    }

    override fun createMetaTileEntity(tileEntity: IGregTechTileEntity) = MultiblockAntimatterGenerator(metaTileEntityId)

    override fun initializeAbilities()
    {
        super.initializeAbilities()
        val outputEnergy = ArrayList(getAbilities(OUTPUT_ENERGY))
        outputEnergy.addAll(getAbilities(SUBSTATION_OUTPUT_ENERGY))
        outputEnergy.addAll(getAbilities(OUTPUT_LASER))
        energyContainer = EnergyContainerList(outputEnergy)
    }

    // @formatter:off

    override fun createStructurePattern(): BlockPattern = FactoryBlockPattern.start()
        .aisle("                DDD                " ,"                DDD                " ,"                DDD                " ,"                DDD                " ,"                 D                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                DDD                " ,"                DDD                " ,"                DDD                " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("               HDDDH               " ,"               HCCCH               " ,"               HCCCH               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("               HDDDH               " ,"               DCCCD               " ,"               HCCCH               " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("               HDDDH               " ,"               HCCCH               " ,"               HCCCH               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("              DDDDDDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"                CCC                " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("            FFDDDDDDDFF            " ,"              DDDDDDD              " ,"              DDDDDDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDDDDDD              " ,"              DDDDDDD              " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("          FFDDDDDDDDDDDFF          " ,"            DDDDG GDDDD            " ,"            DDDDG GDDDD            " ,"            FFCCCCCCCFF            " ,"              CCCCCCC              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"            DDDDDDDDDDD            " ,"             DDDDDDDDD             " ,"            DDDDDDDDDDD            " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DDDCDDD              " ,"            FFDDDDDDDFF            " ,"            DDDDDDDDDDD            " ,"            DDDDDDDDDDD            " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("         FDDDDDDDDDDDDDDDF         " ,"          DDDDGGGGGGGDDDD          " ,"          DDDDGGGGGGGDDDD          " ,"          FFCCGGGGGGGCCFF          " ,"            CC       CC            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"          DDAA   F   AADD          " ,"            AA  FCF  AA            " ,"          DDAA   F   AADD          " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            CCGGGGGGGCC            " ,"          FFCCGGGGGGGCCFF          " ,"          DDDDGGGGGGGDDDD          " ,"          DDDDDDDDDDDDDDD          " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("        FDDDDDDDDDDDDDDDDDF        " ,"         DDDGGDDDDDDDGGDDD         " ,"         DDDGGDDDCDDDGGDDD         " ,"         FCCGG       GGCCF         " ,"          CC           CC          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"         DAA     F     AAD         " ,"          AA    FCF    AA          " ,"         DAA     F     AAD         " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          CCGG       GGCC          " ,"         FCCGGDDDCDDDGGCCF         " ,"         DDDGGDDDDDDDGGDDD         " ,"         DDDDDDDDDDDDDDDDD         " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("       FDDDDDDDDDDDDDDDDDDDF       " ,"        DDGGDDDDDDDDDDDGGDD        " ,"        DDGGDDDDDCDDDDDGGDD        " ,"        FCGG           GGCF        " ,"         C               C         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"        DA       F       AD        " ,"         A      FCF      A         " ,"        DA       F       AD        " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         CGG           GGC         " ,"        FCGGDDDDDCDDDDDGGCF        " ,"        DDGGDDDDDDDDDDDGGDD        " ,"        DDDDDDDDDDDDDDDDDDD        " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("      FDDDDDDDDDDDDDDDDDDDDDF      " ,"       DDGDDDDDGGGGGDDDDDGDD       " ,"       DDGCDDDDGGGGGDDDDCGDD       " ,"       FCG               GCF       " ,"        C                 C        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"       DA       DDD       AD       " ,"        A       CCC       A        " ,"       DA       DDD       AD       " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        CG               GC        " ,"       FCGCDDDDGGGGGDDDDCGCF       " ,"       DDGDDDDDGGGGGDDDDDGDD       " ,"       DDDDDDDDDDDDDDDDDDDDD       " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("      FDDDDDDDDDDDDDDDDDDDDDF      " ,"       DDGDDDGGDDCDDGGDDDGDD       " ,"       DDGDCDGG     GGDCDGDD       " ,"       FCG               GCF       " ,"        C                 C        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"       DA     DD   DD     AD       " ,"        A     CCBBBCC     A        " ,"       DA     DD   DD     AD       " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        CG               GC        " ,"       FCGDCDGG     GGDCDGCF       " ,"       DDGDDDGGDDCDDGGDDDGDD       " ,"       DDDDDDDDDDDDDDDDDDDDD       " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                CCC                " ,"                CCC                " ,"                                   ")
        .aisle("     FDDDDDDDDDDDDDDDDDDDDDDDF     " ,"      DDGDDDGDDDDCDDDDGDDDGDD      " ,"      DDGDDDG         GDDDGDD      " ,"      FCG                 GCF      " ,"       C                   C       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"      DA     D  DDD  D     AD      " ,"       A     CBBDDDBBC     A       " ,"      DA     D  DDD  D     AD      " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       CG                 GC       " ,"      FCGDDDG         GDDDGCF      " ,"      DDGDDDGDDDDCDDDDGDDDGDD      " ,"      DDDDDDDDDDDDDDDDDDDDDDD      " ,"               EEEEE               " ,"               EEEEE               " ,"               EEEEE               " ,"               EEEEE               " ,"               EEEEE               " ,"                CCC                ")
        .aisle("     FDDDDDDDDDDDDDDDDDDDDDDDF     " ,"      DDGDDGDCDGGGGGDCDGDDGDD      " ,"      DDGDDG           GDDGDD      " ,"      FCG                 GCF      " ,"       C                   C       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"      DA    D DD   DD D    AD      " ,"      DA    CBDD   DDBC    AD      " ,"      DA    D DD   DD D    AD      " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       CG                 GC       " ,"      FCGDDG           GDDGCF      " ,"      DDGDDGDCDGGGGGDCDGDDGDD      " ,"      DDDDDDDDDDDDDDDDDDDDDDD      " ,"              E     E              " ,"              E     E              " ,"              E     E              " ,"              E     E              " ,"              EEEEEEE              " ,"                CCC                ")
        .aisle("    DDDDDDDDDDDDDCDDDDDDDDDDDDD    " ,"    DDDGDDDGDDG     GDDGDDDGDDD    " ,"    DDDGDDDG           GDDDGDDD    " ,"    DDCG                   GCDD    " ,"    DDC                     CDD    " ,"    DDD                     DDD    " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD    D D       D D    DD     " ,"     DD    CBD       DBC    DD     " ,"     DD    D D       D D    DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DDG                   GDD     " ,"     DDGDDDG           GDDDGDD     " ,"     DDGDDDGDDG     GDDGDDDGDD     " ,"     DDDDDDDDDDDDCDDDDDDDDDDDD     " ,"             E       E             " ,"             E       E             " ,"             E       E             " ,"             E       E             " ,"             EEEEEEEEE             " ,"                CCC                ")
        .aisle(" HHHDDDDDDDDDDDCCCCCDDDDDDDDDDDHHH " ," HDHDDDGDDGDDG       GDDGDDGDDDHDH " ," HHHDDDGDDG             GDDGDDDHHH " ,"  DDDDCG                   GCDDDD  " ,"   DDDC                     CDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ," DDDDDD    D D       D D    DDDDDD " ," D   DD    CBD       DBC    DD   D " ," DDDDDD    D D       D D    DDDDDD " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDDG                   GDDD    " ,"    DDDGDDG             GDDGDDD    " ,"    DDDGDDGDDG       GDDGDDGDDD    " ,"    DDDDDDDDDDDCCCCCDDDDDDDDDDD    " ,"     DDDDDDDE         EDDDDDDD     " ,"      DDDDDDE         EDDDDDD      " ,"            E         E            " ,"            E         E            " ,"            EEEEEEEEEEE            " ,"                CCC                ")
        .aisle("DDDDDDDDDDDDDDDCGGGCDDDDDDDDDDDDDDD" ,"DCCCCDGGDDGDDG       GDDGDDGGDCCCCD" ,"DCCCCDGGDDG             GDDGGDCCCCD" ,"DCCCCCCG                   GCCCCCCD" ," CCCCCC                     CCCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ,"DCCCCCD   D D         D D   DCCCCCD" ,"DCCCCCDFFFCBD         DBCFFFDCCCCCD" ,"DCCCCCD   D D         D D   DCCCCCD" ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCCDG                   GDCCCCC " ," CCCCCDGDDG             GDDGDCCCCC " ,"  CCCDDGDDGDDG       GDDGDDGDDCCC  " ,"    DDDDDDDDDDDCGGGCDDDDDDDDDDD    " ,"    DDDDDDDDE         EDDDDDDDD    " ,"     DDDDDDDE         EDDDDDDD     " ,"      DDDDDDE         EDDDDDD      " ,"           CE         EC           " ,"           CEEEEEEEEEEEC           " ,"            CCCCCCCCCCC            ")
        .aisle("DDDDDDDDDDDDDDCCGDGCCDDDDDDDDDDDDDD" ,"DCCCCD GDDGCCG       GCCGDDG DCCCCD" ,"DCCCCD GCCG             GCCG DCCCCD" ,"DCCCCCCG                   GCCCCCCD" ,"DCCCCCC                     CCCCCCD" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"DCCCCCDFFFD D         D DFFFDCCCCCD" ,"ICCCCCDCCCCBD         DBCCCCDCCCCCI" ,"DCCCCCDFFFD D         D DFFFDCCCCCD" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCC                       CCCCCF" ,"FCCCCCCG                   GCCCCCCF" ,"FCCCCCDGCCG             GCCGDCCCCCF" ," FCCCDDGDDGCCG       GCCGDDGDDCCCF " ,"  FFDDDDDDDDDDCCGDGCCDDDDDDDDDDFF  " ,"    DDDDDDDDE         EDDDDDDDD    " ,"     DDDDDDDE         EDDDDDDD     " ,"      DDDDDDE         EDDDDDD      " ,"           CE         EC           " ,"           CEEEEEEEEEEEC           " ,"            CCCCCCCCCCC            ")
        .aisle("DDDDDDDDDDDDDDDCGGGCDDDDDDDDDDDDDDD" ,"DCCCCDGGDDGDDG       GDDGDDGGDCCCCD" ,"DCCCCDGGDDG             GDDGGDCCCCD" ,"DCCCCCCG                   GCCCCCCD" ," CCCCCC                     CCCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ,"DCCCCCD   D D         D D   DCCCCCD" ,"DCCCCCDFFFCBD         DBCFFFDCCCCCD" ,"DCCCCCD   D D         D D   DCCCCCD" ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCC                       CCCCC " ," CCCCCDG                   GDCCCCC " ," CCCCCDGDDG             GDDGDCCCCC " ,"  CCCDDGDDGDDG       GDDGDDGDDCCC  " ,"    DDDDDDDDDDDCGGGCDDDDDDDDDDD    " ,"    DDDDDDDDE         EDDDDDDDD    " ,"     DDDDDDDE         EDDDDDDD     " ,"      DDDDDDE         EDDDDDD      " ,"           CE         EC           " ,"           CEEEEEEEEEEEC           " ,"            CCCCCCCCCCC            ")
        .aisle(" HHHDDDDDDDDDDDCCCCCDDDDDDDDDDDHHH " ," HDHDDDGDDGDDG       GDDGDDGDDDHDH " ," HHHDDDGDDG             GDDGDDDHHH " ,"  DDDDCG                   GCDDDD  " ,"   DDDC                     CDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"   DDDD                     DDDD   " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ," DDDDDD    D D       D D    DDDDDD " ," D   DD    CBD       DBC    DD   D " ," DDDDDD    D D       D D    DDDDDD " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDD                     DDD    " ,"    DDDG                   GDDD    " ,"    DDDGDDG             GDDGDDD    " ,"    DDDGDDGDDG       GDDGDDGDDD    " ,"    DDDDDDDDDDDCCCCCDDDDDDDDDDD    " ,"     DDDDDDDE         EDDDDDDD     " ,"      DDDDDDE         EDDDDDD      " ,"            E         E            " ,"            E         E            " ,"            EEEEEEEEEEE            " ,"                CCC                ")
        .aisle("    DDDDDDDDDDDDDCDDDDDDDDDDDDD    " ,"    DDDGDDDGDDG     GDDGDDDGDDD    " ,"    DDDGDDDG           GDDDGDDD    " ,"    DDCG                   GCDD    " ,"    DDC                     CDD    " ,"    DDD                     DDD    " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD    D D       D D    DD     " ,"     DD    CBD       DBC    DD     " ,"     DD    D D       D D    DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DD                     DD     " ,"     DDG                   GDD     " ,"     DDGDDDG           GDDDGDD     " ,"     DDGDDDGDDG     GDDGDDDGDD     " ,"     DDDDDDDDDDDDCDDDDDDDDDDDD     " ,"             E       E             " ,"             E       E             " ,"             E       E             " ,"             E       E             " ,"             EEEEEEEEE             " ,"                CCC                ")
        .aisle("     FDDDDDDDDDDDDDDDDDDDDDDDF     " ,"      DDGDDGDCDGGGGGDCDGDDGDD      " ,"      DDGDDG           GDDGDD      " ,"      FCG                 GCF      " ,"       C                   C       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"      DA    D DD   DD D    AD      " ,"      DA    CBDD   DDBC    AD      " ,"      DA    D DD   DD D    AD      " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       CG                 GC       " ,"      FCGDDG           GDDGCF      " ,"      DDGDDGDCDGGGGGDCDGDDGDD      " ,"      DDDDDDDDDDDDDDDDDDDDDDD      " ,"              E     E              " ,"              E     E              " ,"              E     E              " ,"              E     E              " ,"              EEEEEEE              " ,"                CCC                ")
        .aisle("     FDDDDDDDDDDDDDDDDDDDDDDDF     " ,"      DDGDDDGDDDDCDDDDGDDDGDD      " ,"      DDGDDDG         GDDDGDD      " ,"      FCG                 GCF      " ,"       C                   C       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"      DA     D  DDD  D     AD      " ,"       A     CBBDDDBBC     A       " ,"      DA     D  DDD  D     AD      " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       A                   A       " ,"       CG                 GC       " ,"      FCGDDDG         GDDDGCF      " ,"      DDGDDDGDDDDCDDDDGDDDGDD      " ,"      DDDDDDDDDDDDDDDDDDDDDDD      " ,"               EEEEE               " ,"               EEEEE               " ,"               EEEEE               " ,"               EEEEE               " ,"               EEEEE               " ,"                CCC                ")
        .aisle("      FDDDDDDDDDDDDDDDDDDDDDF      " ,"       DDGDDDGGDDCDDGGDDDGDD       " ,"       DDGDCDGG     GGDCDGDD       " ,"       FCG               GCF       " ,"        C                 C        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"       DA     DD   DD     AD       " ,"        A     CCBBBCC     A        " ,"       DA     DD   DD     AD       " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        CG               GC        " ,"       FCGDCDGG     GGDCDGCF       " ,"       DDGDDDGGDDCDDGGDDDGDD       " ,"       DDDDDDDDDDDDDDDDDDDDD       " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                CCC                " ,"                CCC                " ,"                                   ")
        .aisle("      FDDDDDDDDDDDDDDDDDDDDDF      " ,"       DDGDDDDDGGGGGDDDDDGDD       " ,"       DDGCDDDDGGGGGDDDDCGDD       " ,"       FCG               GCF       " ,"        C                 C        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"       DA       DDD       AD       " ,"        A       CCC       A        " ,"       DA       DDD       AD       " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        A                 A        " ,"        CG               GC        " ,"       FCGCDDDDGGGGGDDDDCGCF       " ,"       DDGDDDDDGGGGGDDDDDGDD       " ,"       DDDDDDDDDDDDDDDDDDDDD       " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("       FDDDDDDDDDDDDDDDDDDDF       " ,"        DDGGDDDDDDDDDDDGGDD        " ,"        DDGGDDDDDCDDDDDGGDD        " ,"        FCGG           GGCF        " ,"         C               C         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"        DA       F       AD        " ,"         A      FCF      A         " ,"        DA       F       AD        " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         A               A         " ,"         CGG           GGC         " ,"        FCGGDDDDDCDDDDDGGCF        " ,"        DDGGDDDDDDDDDDDGGDD        " ,"        DDDDDDDDDDDDDDDDDDD        " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("        FDDDDDDDDDDDDDDDDDF        " ,"         DDDGGDDDDDDDGGDDD         " ,"         DDDGGDDDCDDDGGCDD         " ,"         FCCGG       GGCCF         " ,"          CC           CC          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"         DAA     F     AAD         " ,"          AA    FCF    AA          " ,"         DAA     F     AAD         " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          AA           AA          " ,"          CCGG       GGCC          " ,"         FCCGGDDDCDDDGGCCF         " ,"         DDDGGDDDDDDDGGDDD         " ,"         DDDDDDDDDDDDDDDDD         " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("         FDDDDDDDDDDDDDDDF         " ,"          DDDDGGGGGGGDDDD          " ,"          DDDDGGGGGGGDDDD          " ,"          FFCCGGGGGGGCCFF          " ,"            CC       CC            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"          DDAA   F   AADD          " ,"            AA  FCF  AA            " ,"          DDAA   F   AADD          " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            AA       AA            " ,"            CCGGGGGGGCC            " ,"          FFCCGGGGGGGCCFF          " ,"          DDDDGGGGGGGDDDD          " ,"          DDDDDDDDDDDDDDD          " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("          FFDDDDDDDDDDDFF          " ,"            DDDDG GDDDD            " ,"            DDDDG GDDDD            " ,"            FFCCCCCCCFF            " ,"              CCCCCCC              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"            DDDDDDDDDDD            " ,"             DDDDDDDDD             " ,"            DDDDDDDDDDD            " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DD   DD              " ,"              DDDCDDD              " ,"            FFDDDDDDDFF            " ,"            DDDDDDDDDDD            " ,"            DDDDDDDDDDD            " ,"               DDDDD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("            FFDDDDDDDFF            " ,"              DDDDDDD              " ,"              DDDDDDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDDDDDD              " ,"              DDDDDDD              " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("              DDDDDDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"              DDCCCDD              " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"                CCC                " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DDDDD               " ,"                DDD                " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("               HDDDH               " ,"               HCCCH               " ,"               HCCCH               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("               HDDDH               " ,"               DCCCD               " ,"               HCCCH               " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("               HDDDH               " ,"               HCCCH               " ,"               HCCCH               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"               DCCCD               " ,"               DCCCD               " ,"               DCCCD               " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                CCC                " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .aisle("                DDD                " ,"                D~D                " ,"                DDD                " ,"                DDD                " ,"                 D                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                DDD                " ,"                DDD                " ,"                DDD                " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                 F                 " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   " ,"                                   ")
        .where('~', selfPredicate())
        .where('D', states(casingState))
        .where('G', states(coilState))
        .where('B', states(secondCoilState))
        .where('C', states(secondCasingState))
        .where('A', states(glassState))
        .where('E', states(thirdCasingState))
        .where('H', states(secondCasingState)
            .or(abilities(OUTPUT_ENERGY)
                .setPreviewCount(0))
            .or(abilities(OUTPUT_LASER)
                .setPreviewCount(72)))
        .where('I', states(casingState)
            .or(abilities(IMPORT_FLUIDS)
                .setPreviewCount(2)))
        .where('F', frames(Naquadria))
        .where(' ', any())
        .build()

    // @formatter:on

    @SideOnly(Side.CLIENT)
    override fun getBaseTexture(sourcePart: IMultiblockPart?): ICubeRenderer
            = if (recipeMapWorkable.isActive) GTLiteOverlays.ANTIMATTER_FORGE_ACTIVE_TEXTURE else GTLiteOverlays.ANTIMATTER_FORGE_TEXTURE

    @SideOnly(Side.CLIENT)
    override fun getFrontOverlay(): ICubeRenderer = GTLiteOverlays.ANTIMATTER_FORGE_OVERLAY

    override fun addInformation(stack: ItemStack, world: World?, tooltip: MutableList<String>, advanced: Boolean)
    {
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.1"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.2"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.3"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.4"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.5"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.6"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.7"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.8"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.9"))
        tooltip.add(I18n.format("gtlitecore.machine.antimatter_generator.tooltip.10"))
    }

    override fun canBeDistinct() = false

    override fun shouldShowVoidingModeButton() = false

    override fun hasMaintenanceMechanics() = false

    private inner class AntimatterGeneratorWorkableHandler(mte: RecipeMapMultiblockController) : MultiblockFuelRecipeLogic(mte)
    {

        override fun isAllowOverclocking() = true

    }

}